version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # AJOUT: 'always' au lieu de 'unless-stopped' pour garantir que le service redémarre toujours
    restart: always
    volumes:
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    environment:
      - APP_ENV=production
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=businesscare2
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      - db # lancera le service db avant de lancer le service app
    ports:
      - "8000:80"
    networks:
      - businesscare-network

  db:
    image: mariadb:11.7
    # AJOUT: 'always' pour assurer la haute disponibilité en production
    restart: always
    environment:
      - MYSQL_DATABASE=businesscare2
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./database/repInit:/docker-entrypoint-initdb.d
    ports:
      - "3308:3306"

    networks:
      - businesscare-network


  portainer:
    image: portainer/portainer-ce:latest
    # AJOUT: 'always' au lieu de 'unless-stopped'
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    ports:
      - "9000:9000"
    networks:
      - businesscare-network

volumes:
  mariadb-data:
  portainer-data:

networks:
  businesscare-network:
    driver: bridge
