version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/html  # Volume pour le développement (hot-reload)
    environment:
      - APP_ENV=development
      - DB_HOST=database
      - DB_PORT=3306
      - DB_DATABASE=businesscare
      - DB_USERNAME=user
      - DB_PASSWORD=password
    depends_on:
      - database
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:80"  # Changé à 3000 pour éviter les conflits
    depends_on:
      - backend
    networks:
      - app-network

  database:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: businesscare
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql  # Volume persistant pour les données
    ports:
      - "3308:3306"
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
