version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./:/var/www/html:cached
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3308
      - DB_DATABASE=businesscare
      - DB_USERNAME=root
      - DB_PASSWORD=root
    depends_on:
      - db
    ports:
      - "8000:80"
    networks:
      - businesscare-network

  db:
    image: mariadb:10.6
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=businesscare
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./database/dataSave:/var/lib/mysql # les données
      - ./database/repInit:/docker-entrypoint-initdb.d # les tables
    ports:
      - "3333:3308"
    command: --port=3308 # changement de port pour rester sur 3308, sinon marche pas
    networks:
      - businesscare-network

  portainer:
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    ports:
      - "9000:9000"
    networks:
      - businesscare-network

volumes:
  mariadb-data:
  portainer-data:

networks:
  businesscare-network:
