
version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=businesscare2
      - DB_USERNAME=root
      - DB_PASSWORD=root

    command: >
      sh -c "chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache &&
            chmod -R 775 /var/www/html/storage /var/www/html/bootstrap/cache &&
            php artisan config:cache &&
            /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf"
    depends_on:
      - db
    ports:
      - "8000:80"
    networks:
      - businesscare-network
  db:
    image: mariadb:11.7
    restart: always
    environment:
      - MYSQL_DATABASE=businesscare2
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./database/repInit:/docker-entrypoint-initdb.d
    ports:
      - "3308:3306"
    networks:
      - businesscare-network
  portainer:
    image: portainer/portainer-ce:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    ports:
      - "9000:9000"
    networks:
      - businesscare-network
volumes:
  mariadb-data:
  portainer-data:
networks:
  businesscare-network:
    driver: bridge
